swagger: "2.0"
info:
  description: "This is an API for BankaApp app at Andela Bootcamp."
  version: "1.0.0"
  title: "Banka App API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "adeyemi_adekorede@hotmail.com"
  license:
    name: "MIT"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "bankaandela.herokuapp.com"
basePath: "/api/v1"
tags:
- name: "user"
  description: "Operations about user"
schemes:
- "https"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
paths:
  /auth/signup:
    post:
      tags:
      - "user"
      summary: "create a new user"
      operationId: "SignUpUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User sign-up details"
        required: true
        schema:
          $ref: "#/definitions/SignUp"
      responses:
        200:
          description: "USER sign up succesfull"
          schema:
            $ref: "#/definitions/SignUpResponse"
        401:
          description: "Auth failed"
        404:
          description: "user not found"
definitions:
  SignUp:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
        format: "email"
      password:
        type: "string"
        format: "password"
      Type:
        type: "string"
      isAdmin: 
        type: "boolean"
        
  SignUpResponse:
    type: "object"
    properties:
       status:
         type: "string"
       Data:
         type: "object"
         properties:
           id:
             type: "integer"
             format: "int32"
           firstname:
             type: "string"
           lastname: 
             type: "string"
           email:
             type: "string"
             format: "email"
           password: 
             type: "string"
           photo:
             type: "string"
           type:
             type: "string"
           isAdmin: 
             type: "boolean"
           createdon:
             type: "string"
             format: "date-time"
           token:
             type: "string"
      


